query getFlimsRelative($id: String) {
  alsoLikeFlims(id: $id) {
    info {
      name
      poster
    }
    data {
      rottenTomatoes {
        tomatometerScore
        audienceScore
      }
    }
    slug
  }
}
