query getFlimBySlug($slug: String) {
  flimBySlug(slug: $slug) {
    id
    type
    userScore
    lemonScore
    userReviewCount
    lemonReviewCount
    info {
      name
      tags
      genres
      poster
      rating
      runtime
      summary
      trailer
      collection
      soundMixs
      productions
      aspectRatio
      theatersDate
      streamingDate
      originalLanguage
    }
    whatToKnows {
      title
      content
    }
    streamings
    photos
    crews {
      role
      person {
        id
        name
        slug
        images
      }
    }
    quotes {
      name
      content
    }
    data {
      news {
        title
        content
        data {
          section
          previewPoster
        }
        slug
      }
      trailerPhoto
      rottenTomatoes {
        audienceScore
        tomatometerScore
      }
    }
    createdAt
    updatedAt
  }
}
