query getFlimsByParams(
  $page: Int
  $size: Int
  $type: String
  $sortKey: String
  $params: JSON
) {
  flimsByParams(
    page: $page
    size: $size
    type: $type
    sortKey: $sortKey
    params: $params
  ) {
    results {
      info {
        name
        poster
        rating
        runtime
        summary
      }
      data {
        rottenTomatoes {
          tomatometerScore
        }
      }
      slug
      createdAt
    }
    count
  }
}
