query getMenuPosts {
  menuPosts {
    frames {
      data {
        previewPoster
      }
      title
      slug
    }
    guides {
      data {
        previewPoster
      }
      title
      slug
    }
    latest {
      data {
        previewPoster
      }
      title
      slug
    }
  }
}
