query getPostBySlug($slug: String) {
  postBySlug(slug: $slug) {
    user {
      name
      slug
    }
    title
    sideTitle
    content
    updatedAt
    comments {
      id
      user {
        name
        slug
        image
      }
      content
      score
      childComments {
        id
        user {
          name
          slug
          image
        }
        score
        content
      }
      interacts {
        user {
          name
          slug
          image
        }
        emoji
        score
      }
    }
    interacts {
      user {
        name
        slug
        image
      }
      emoji
      score
    }
  }
}
