query getNews($page: Int, $size: Int, $type: String, $section: String) {
  posts(page: $page, size: $size, type: $type, section: $section) {
    count
    results {
      title
      data {
        previewPoster
      }
      slug
      createdAt
    }
  }
}
