query getPostBySlug($slug: String) {
  postBySlug(slug: $slug) {
    id
    user {
      id
      name
      slug
    }
    title
    sideTitle
    content
    updatedAt
    comments {
      id
      user {
        id
        name
        slug
        image
        role
        data {
          working
        }
      }
      content
      score
      childComments {
        id
        user {
          id
          name
          slug
          image
          role
          data {
            working
          }
        }
        interacts {
          id
          user {
            id
            name
            slug
            image
            role
            data {
              working
            }
          }
          emoji
        }
        score
        content
        updatedAt
      }
      interacts {
        id
        user {
          id
          name
          slug
          image
          role
          data {
            working
          }
        }
        emoji
        score
      }
      updatedAt
    }
    interacts {
      id
      user {
        id
        name
        slug
        image
        role
        data {
          working
        }
      }
      emoji
      score
    }
  }
}
