query getUserInfo($token: String) {
  getUserInfo(token: $token) {
    reviews {
      id
      title
      slug
      updatedAt
      data {
        score
        flim {
          lemonScore
          userScore
          info {
            name
            poster
            summary
            theatersDate
          }
          slug
        }
      }
    }
    news {
      id
      title
      slug
      updatedAt
      data {
        previewPoster
        section
      }
    }
    histories {
      id
      type
      data
      post
      updatedAt
    }
  }
}
